<?php

/**
 * @file
 * Falcon_commerce.module file.
 */

use Drupal\commerce_price\Price;

/**
 * Implements hook_modules_installed().
 *
 * Create donation product and product variation once Falcon Donation feature is
 * installed.
 */
function falcon_commerce_modules_installed($modules) {
  if (!in_array('falcon_feature_donation', $modules)) {
    return;
  }

  $entity_type_manager = \Drupal::entityTypeManager();
  $stores = $entity_type_manager->getStorage('commerce_store')->loadByProperties(['type' => 'online']);

  // Create product variation.
  $variation = $entity_type_manager->getStorage('commerce_product_variation')->create([
    'type' => 'donation',
    'title' => 'Donation',
    'sku' => 'donation',
    'status' => 1,
    'price' => new Price('0', 'EUR'),
  ]);
  $variation->save();

  // Create product.
  $product = $entity_type_manager->getStorage('commerce_product')->create([
    'uid' => 1,
    'type' => 'donation',
    'title' => 'Donation',
    'stores' => $stores,
    'variations' => [$variation],
  ]);
  $product->save();
}
