<?php

/**
 * @file
 * Falcon_gift_ecards.module file.
 */

/**
 * Implements hook_order_checkout_prepare_alter().
 *
 * @param array $data
 *   Array of sent data to commerce/order/create.
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function falcon_gift_ecards_order_checkout_prepare_alter(array &$data) {
  foreach ($data['order']['order_items'] as $key => $item) {
    if (array_key_exists('field_card_delivery', $item) &&
      $item['field_card_delivery'] === 'email' &&
      !empty($item['field_card'])) {

      $storage = Drupal::entityTypeManager()->getStorage('letters');
      $entityData = $item['field_card'];
      $entityData['type'] = 'ecard';

      try {
        $entity = $storage->create($entityData);
        $entity->save();

        $data['order']['order_items'][$key]['field_card'] = $entity->id();
      }
      catch (Exception $e) {
        Drupal::logger('falcon_gift_ecards')->alert($e->getMessage());
      }
    }
  }

}

/**
 * Implements hook_mail().
 *
 * Captures the outgoing mail and sets appropriate message body and headers.
 */
function falcon_gift_ecards_mail($key, &$message, $params) {
  switch ($key) {
    case 'ecard_mail':
      if (isset($params['headers'])) {
        $message['headers'] = array_merge($message['headers'], $params['headers']);
      }

      $message['format'] = 'text/html';
      $message['from'] = $params['from'];
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];

  }
}
