<?php

namespace falcon_feature_metatag;

/**
 * Class MetatagCest.
 *
 * @package Falcon Configurations
 */
class MetatagCest {

  private $appeal;

  /**
   *
   * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
   * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
   * @throws \Drupal\Core\Entity\EntityStorageException
   */
  public function _before() {
    // Create appeal.
    $this->appeal = \Drupal::entityTypeManager()->getStorage('node')->create([
      'uid' => 1,
      'type' => 'appeal',
      'title' => 'Test appeal',
      'status' => 1,
      'field_meta_tags' => serialize([
        'description' => 'TEST DESCRIPTION',
        'keywords' => 'TEST KEYWORDS'
      ])
    ]);
    $this->appeal->save();
  }

  /**
   * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
   * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
   * @throws \Drupal\Core\Entity\EntityStorageException
   */
  public function _after() {
    \Drupal::entityTypeManager()->getStorage('node')->delete([$this->appeal]);
  }

  /**
   * Normalized metatags into jsonApi response.
   *
   * @param \ApiTester $I
   * @group basic
   */
  public function metatagsInResponse(\ApiTester $I) {
    $I->amGoingTo('Get request to JsonAPI endpoint. Checks metatags in response.');
    $I->haveHttpHeader('Content-Type', 'application/json');

    $consumers = \Drupal::entityTypeManager()
        ->getStorage('consumer')
        ->loadByProperties(['label' => 'Falcon']);

    $consumer = array_pop($consumers);

    // Set consumer header.
    if (!empty($consumer)) {
      $I->haveHttpHeader('X-Consumer-ID', $consumer->uuid());
    }

    $path_prefix = \Drupal::config('jsonapi_extras.settings')
      ->get('path_prefix');

    $I->sendGET("/$path_prefix/node/appeal");

    $I->expectTo('See normalized metatags in response.');
    $I->seeResponseJsonMatchesJsonPath('$.data..attributes.metatag_normalized');

    $I->expectTo('See metatag title "Test appeal | Falcon" in response that generated by consumers_token module');
    $I->seeResponseContainsJson(['content' => 'Test appeal | Falcon', 'name' => 'title']);

    $I->expectTo('See metatag descripotion "TEST DESCRIPTION." in response.');
    $I->seeResponseContainsJson(['content' => 'TEST DESCRIPTION', 'name' => 'description']);

    $I->expectTo('See metatag keywords "TEST KEYWORDS." in response.');
    $I->seeResponseContainsJson(['content' => 'TEST KEYWORDS', 'name' => 'keywords']);
  }

}
