images:
  php:
    repository: "675226414167.dkr.ecr.eu-west-1.amazonaws.com/falcon-php"
  nginx:
    repository: "675226414167.dkr.ecr.eu-west-1.amazonaws.com/falcon-nginx"
  node:
    repository: "675226414167.dkr.ecr.eu-west-1.amazonaws.com/falcon-node"

dbOperator:
  masterPasswordAWSSecretKey: "DB_MASTER_PASSWORD"
