<?php

/**
 * @file
 * Falcon_common.install file.
 */

/**
 * Implements hook_install().
 */
function falcon_common_install() {
  // Create default consumer.
  $consumer = \Drupal::entityTypeManager()->getStorage('consumer')->create([
    'uuid' => '114e3e1a-6f65-49a8-9a24-v0043fabd6e7',
    'type' => 'consumer',
    'label' => 'Falcon Frontend Application',
    'image_styles' => [['target_id' => 'full_size']],
  ]);
  $consumer->save();
}
